/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomSideDrawer {
        /**
          * @Method make the open function expose to light DOM
         */
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface ExchangeRate {
    }
    interface StockPrice {
        "stockSymbol": string;
        "title": string;
    }
}
declare global {
    interface HTMLCustomSideDrawerElement extends Components.CustomSideDrawer, HTMLStencilElement {
    }
    var HTMLCustomSideDrawerElement: {
        prototype: HTMLCustomSideDrawerElement;
        new (): HTMLCustomSideDrawerElement;
    };
    interface HTMLExchangeRateElement extends Components.ExchangeRate, HTMLStencilElement {
    }
    var HTMLExchangeRateElement: {
        prototype: HTMLExchangeRateElement;
        new (): HTMLExchangeRateElement;
    };
    interface HTMLStockPriceElement extends Components.StockPrice, HTMLStencilElement {
    }
    var HTMLStockPriceElement: {
        prototype: HTMLStockPriceElement;
        new (): HTMLStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "custom-side-drawer": HTMLCustomSideDrawerElement;
        "exchange-rate": HTMLExchangeRateElement;
        "stock-price": HTMLStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface CustomSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface ExchangeRate {
    }
    interface StockPrice {
        "stockSymbol"?: string;
        "title"?: string;
    }
    interface IntrinsicElements {
        "custom-side-drawer": CustomSideDrawer;
        "exchange-rate": ExchangeRate;
        "stock-price": StockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-side-drawer": LocalJSX.CustomSideDrawer & JSXBase.HTMLAttributes<HTMLCustomSideDrawerElement>;
            "exchange-rate": LocalJSX.ExchangeRate & JSXBase.HTMLAttributes<HTMLExchangeRateElement>;
            "stock-price": LocalJSX.StockPrice & JSXBase.HTMLAttributes<HTMLStockPriceElement>;
        }
    }
}
